#This file builds the Docker images for a React/NodeJS application and runs it as microservices on Docker containers

#To ensure successful execution, clone this entire repository and execute this file while in the root folder of the cloned repository

#It's also a requirement to have Docker and the docker-compose plugin installed in your environment

#To launch this app without having to clone the entire repository,use the docker-compose.yaml file to run the app

services:

  #Builds the frontend Docker image and creates the frontend microservice
  nyange-new-yolo-client:
    image: majangajohn/nyange-yolo-client:v2.0.0
    build: 
      context: ./client
    container_name: nyange-new-yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider # enables legacy crypto for webpack)
    depends_on: 
      - nyange-new-yolo-backend
    networks:
      - app-net

  #Builds the backend Docker image and creates the backend microservice
  nyange-new-yolo-backend:
    image: majangajohn/nyange-yolo-backend:v2.0.0
    build: 
      context: ./backend
    container_name: nyange-new-yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://app-new-ip-mongo:27017/yolomy
    depends_on: 
      - app-new-ip-mongo
    networks:
      - app-net

  #Creates the database microservice
  app-new-ip-mongo:
    image: mongo
    container_name: app-new-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-new-mongo-data
        target: /data/db

#Creates the network infrastructure necessary for the containers to communicate with each other
networks:
  app-net:
    name: app-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16 
          ip_range: 172.20.0.0/16  # fall back to default if the subnet is taken

#Creates a Docker volume that persists all the data stored in the database
volumes:
  app-new-mongo-data:
    driver: local